### ISSUE TITLE
Bounty for destroyed transport

### ISSUE THREAD

**Issue by Sindeg** [majorwolf/Arma3-Liberation-ACE-RHS#1]
Find your ver. of lib really useful. Is it possible to fix bound system for transport ? Seems the problem in condition.

**Comment by majorwolf** [comment]
Bounties for destroying RHS vehicles?

**Comment by majorwolf** [comment]
@sindeg

**Comment by Sindeg** [comment]
exactly! For example : light tech - 10 , heavy - 20 , air - 40 . as vanilia liberation

**Comment by GreuhZbug** [comment]
Copied from the forums:

> I didn't look into it but I'm going to guess that the class hierarchy in RHS doesn't match the vanilla game at all, since all the stuff that inherits from Car, Tank and Air will get a bounty

**Comment by majorwolf** [comment]
@GreuhZbug So the way liberation is structured it just classifies units as Car, Tank, or Air? I thought you could add the classnames for the bounties as individual objects

**Comment by GreuhZbug** [comment]
Noes, the bounties system doesn't manage a bunch of individual classnames (tho maybe it could). The code is in kill_manager.sqf, lines 81 to 88. I suppose you could add a bunch of other superclasses there, or even actual classnames? iirc RHS uses stuff like "APC" and so on

**Comment by majorwolf** [comment]
@Sindeg What specific transports are you talking about? Transport Heli's or the Ural Transport

**Comment by majorwolf** [comment]
@GreuhZbug Assuming it will respect the configs parent structure I should be able to add individual rhs vehicles if they aren't already covered by the "Tank" or "Air" parents. Some of these transports fall under "Truck". Here: [http://class.rhsmods.org/rhsafrf/CfgVehicles_Heli_Attack_02_base_F.html](url) I'm thinking I'll be able to probably add this type and it will cover the Mi24 and the Ka52 respectively but that's already covered by "Air" so that would be pointless.

EDIT: For instance the Ural trucks I should be able to add "RHS_Ural_Base" to cover all the variants.

**Comment by Sindeg** [comment]
I would be very grateful, if you wouldd  show how i can try to edit code, make own lists, for example, to light vehicle, heavy etc. ( you do not have to create these lists, i`ll try myself )

>  I suppose you could add a bunch of other superclasses there, or even actual classnames
